version: "3.8"

services:
    mongo:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password

    postgres:
        image: postgres
        container_name: postgresdb
        restart: always
        ports:
            - "54320:5432"
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
